name: webpack-bundle
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches:
      - main
jobs:
  start deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    
    steps:
      - uses: actions/checkout@v4
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install 
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
